ledgersmb/ledgersmb-dev-docker

docker-compose.yml
Is_LSMB_running.sh defaults to http://localhost:5001, but this container
uses port 5762, so an environment variable needs to be set.
=> Add env variable $PSGI_BASE_URL so Is_LSMB_running.sh works

docker-compose.yml
Failing to explicitly set the LANG variable for the selenium container causes tests involving
date formats to fail when the dojo date widget expects a different
date format to that used in the test definitions.
An example of such a test is xt/66-cucumber/01-basic/setup.feature
=> Add LANG environment variable for selenium container

ledgersmb/Dockerfile
Apologies - previous commit introduced a Dockerfile syntax error by
missing a line continutation character in the list of packages to
install. I now know how to test locally first :)
=> Fix Dockerfile missing line continuation in previous commit

docker-compose.yml
Environment variable `LSMB_IMAGE` may be used to specify the docker
image used for the lsmb/starman container.
By default, the previously hard-coded `ledgersmb/ledgersmb-dev-lsmb`
is used, but this can now be overridden by the enviroment variable.
This allows the same official `docker-compose.yml` file to be used with
alternative images, perhaps for testing a specific perl version.
=> Add LSMB_IMAGE variable for lsmb image name in docker-compose.yml

docker-compose.yml
* Drop disused environment variable `POD_TESTING`
* Add `COA_TESTING=1` to enable coa testing by default
=> Update environment variables - enable COA_TESTING

README.md, docker-compose.yml, tools/make_perl_context
This adds a script for creating a new docker context from which a local ledgersmb development image can be built, based from a specified version of the official perl containers.
This provides a standardised and repeatable route to testing lsmb against a particular version of perl.
I think there is value to including this tool, but won't be offended if the consensus is not to.
The script copies `README.md`, `start.sh`,  `update_ssmtp.sh` from the official `ledgersmb`  build context, but creates a new Dockerfile. This new Dockerfile differs from the official Dockerfile in the following ways:
* Based on `perl:5.xx` image, rather than `debian:stretch`
* Doesn't install perl dependencies using `apt-get` as the official perl containers don't use system perl libraries.
* Doesn't install lsmb …
=> Add script to create build context for testing different perl versions

lsmb-dev
When I added `is_container_running()` I left a hadrcoded container name.
This commit fixes that.
=> use container name variable everywhere!

lsmb-dev
- Insert an `_` after the `ld` prefix for the container names
This improves human readability
=> improve formatting of the container names

README.md, docker-compose.yml, ledgersmb/start.sh
Default configuration updated so that mail sent from lsmb is
directed to the MailHog container.
The MailHog container accepts smtp connections on port 1025.
It provides a web UI and api to view and retrieve messages on
port 8025.
=> Add MailHog to catch e-mail sent during lsmb development

README.md
Commit b85b463c84bc30dd0dfb6794ef3c1ae9b5bba230
removed use of the `$LSMB_DEV_VERSION` environment variable.
This commit updates the README to reflect this change.
=> Update README to reflect removal of LSMB_DEV_VERSION variable

ledgersmb/Dockerfile
In order to be used as a primary container on CircleCI, a custom Docker image must have git, ssh, tar, gzip and ca-certificates installed
=> Add CircleCI primary container requirements

.gitignore, README.md, docker-compose.yml, ledgersmb/Dockerfile, ledgersmb/start.sh, lsmb-dev, nginx/nginx.conf, selenium/docker-compose-chrome.yml, selenium/docker-compose-firefox.yml, selenium/docker-compose-operablink.yml, selenium/docker-compose.yml
This PR departs from PhantomJS to the profit of a Selenium Grid. Chrome, Firefox or Opera can be used.
It also maps the host user to the working user in the `lsmb` container and bind mount the home directory so that the user is defined.
Finally, it maps the proxy server to 5000 instead of 80 to remove conflicts with existing installations.
=> Move from PhantomJS to a Selenium grid

nginx/nginx.conf
Allow the proxy to send gzipped statics instead of the no-compressed versions when available and allowed by the client
=> Allow using gzipped statics

docker-compose.yml, lsmb-dev
Add capability to map the Postgres database to the host to allow access for inspection
The port can be optionaly defined with environment variable DB_PORT.
The link will be shown upon container startup
=> Allow mapping Postgres database to host port

docker-compose.yml
Remove syntax error in docker-compose brought by bad indentation
=> Fix spurious indentation in docker-compose

.github/workflows/docker-image.yml
Answer to a build request from LedgerSMB/master merge to synchronize the development docker images
=> Allow triggered build from Ledgersmb/master merge

.github/workflows/docker-image.yml
Remote triggered builds only concern ledgersmb, not the proxy or the database
=> Only rebuild ledgersmb on master changes

ledgersmb/Dockerfile
Allow `make dojo` to work on a 1.5 branch
=> Add 1.5 requirements

ledgersmb/Dockerfile
Having pg_autodoc installed helps to regenerate the schema documentation.
=> Install 'postgresql_autodoc' in the dev image

README.md, lsmb-dev
Add 2 additional ports that were present but not reported
Reformat the reported ports into sections for external and internal
Change the 'db' line to be a postgres URL for consistency with other URLs
Minor revisions to README.md for grammer and clarity
Correct error in how tests are run in parallel in README.md
=> Revise ports reported during startup
