ledgersmb/Dockerfile
This is a development container. It's useful to be able to test
these features.
=> Add feature options xls and edi to Dockerfile

ledgersmb/Dockerfile
* Remove non-existent 1.5 feature 'xls'
* Add master feature 'latex-pdf-images'
=> Update lsmb features in Dockerfile

.gitignore, lsmb-dev
This PR adds
- better error handling
- provision for a local config file
- detection / confirmation that we are running from a ledgersmb repo
- detection and option to restart a running lsmb container
=> Add local config file, error handling, and more

selenium/docker-compose-chrome.yml, selenium/docker-compose-firefox.yml, selenium/docker-compose-operablink.yml, selenium/docker-compose.yml
Make sure that we stay on Selenium 3 for we are not yet compatible with the version 4
=> Force usage of Selenium version 3

docker-compose.yml
Add a suitable default for a directory to be used as $HOME in the docker environment
=> Add default for HOME_DEV

lsmb-dev
Removes indentation of host & db links
=> Fix links display

lsmb-dev
=> Make sure docker-compose-local is used when available

README.md
Document recent changes on environment variables usage and useable links
=> Fix user documentation

.github/workflows/docker-image.yml, ledgersmb/Dockerfile
Auto-build and push on docker hub using GA workflow.
=> Add GitHub workflow

.github/workflows/docker-image.yml
Triggered rebuild from LedgerSMB/master only concerns ledgersmb, not the proxy nor the database
=> Only rebuild ledgersmb on master changes

.github/workflows/docker-image.yml
Reverts ledgersmb/ledgersmb-dev-docker#31
=> Revert "Only rebuild ledgersmb on master changes"

README.md, tools/make_perl_context
Adjust for new ledgersmbdev Docker repository
=> Fix location of docker images

.github/workflows/docker-image.yml
=> Move identification to GITHUB_TOKEN

.github/workflows/docker-image.yml
Reverts ledgersmb/ledgersmb-dev-docker#35
=> Revert "Move identification to GITHUB_TOKEN"

.github/workflows/docker-image.yml, lsmb-dev
Fix reference for user environment variables file
=> Fix misspelled variable

ledgersmb/Dockerfile, ledgersmb/start.sh, lsmb-dev, postgres/Dockerfile, postgres/lsmb-dev-init.sh
- Simplify the ledgersmb/Dockerfile so that we can select previous branches to include
- Fix pgdata location to enable PG configuration
- Build dojo at runtime instead of build time
- Create the HOME directory to prevent docker-compose to create it on first mount and assign it to root
=> Simplify configuration

README.md, lsmb-dev
1- Adjust README with the selenium hub addition
2- Adjust DB link shown
=> Adjust documentation [skip_ci]

docker-compose.yml
Add 2 environment variables for UI testing
=> Add jstest environment variables

README.md
This addresses https://github.com/ledgersmb/LedgerSMB/issues/4751 by adding a new section at the bottom of the readme.
=> Changes to satisify https://github.com/ledgersmb/LedgerSMB/issues/4751

nginx/nginx.conf
Restore gzip compression for proxy delivered elements
=> Add gzip compression

README.md
in order for the tests to run correctly.
=> Add comment that DB namespace must be set to xyz
